<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Dieta>
 */
class DietaFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'nome'=> $this->faker->word(),
            'cafe' => $this->faker->randomElement([
                'Pão de queijo',
                'Tapioca',
                'Mingau de aveia',
                'Omelete',
                'Frutas',
                'Iogurte com granola',
                'Cereal matinal',
                'Vitamina de frutas',
                'Panqueca de banana',
                'Smoothie de morango',
                'Pão integral com queijo',
                'Café preto',
                'Chá verde',
                'Waffle com mel',
                'Sanduíche de peito de peru',
                'Torrada com abacate',
                'Bolo de cenoura',
                'Muffin de blueberry',
                'Croissant',
                'Cuscuz com ovos',
            ]),
            'lanche1' => $this->faker->randomElement([
                'Sanduíche natural',
                'Salada de frutas',
                'Barra de cereal',
                'Biscoitos integrais',
                'Iogurte grego',
                'Pipoca',
                'Smoothie de manga',
                'Shake de proteína',
                'Bolinho de arroz',
                'Batata doce cozida',
                'Queijo cottage',
                'Gelatina',
                'Cookies de aveia',
                'Suco de laranja natural',
                'Cenourinhas baby',
                'Pão de forma com peito de peru',
                'Cookies de chocolate',
                'Muffin de banana',
                'Torrada com patê',
                'Tapioca recheada',
            ]),
            'almoco' => $this->faker->randomElement([
                'Arroz, feijão, frango e salada',
                'Peixe grelhado, batata doce e legumes',
                'Macarrão integral com molho de tomate e carne moída',
                'Strogonoff de carne com arroz e salada',
                'Feijoada light',
                'Risoto de cogumelos',
                'Salmão assado com purê de batatas',
                'Salada de quinoa com frango desfiado',
                'Carne assada com legumes',
                'Frango xadrez com arroz integral',
                'Espaguete ao pesto',
                'Yakisoba de legumes',
                'Sopa de legumes',
                'Lasanha de berinjela',
                'Cuscuz paulista',
                'Tilápia ao molho de maracujá',
                'Torta de frango',
                'Berinjela recheada',
                'Salada de grão de bico',
                'Pizza integral de vegetais',
            ]),
            'lanche2' => $this->faker->randomElement([
                'Pão de queijo',
                'Barrinha de cereal',
                'Ovos cozidos',
                'Castanhas',
                'Iogurte natural',
                'Frutas secas',
                'Gelatina diet',
                'Suco de fruta',
                'Smoothie de abacate',
                'Torradas integrais',
                'Muffin de maçã',
                'Pipoca sem óleo',
                'Bolo de fubá',
                'Cookies integrais',
                'Muffin de cenoura',
                'Tortinha de frango',
                'Sanduíche de atum',
                'Crepioca',
                'Salada de frango',
                'Queijo com presunto',
            ]),
            'janta' => $this->faker->randomElement([
                'Sopa de legumes',
                'Salada caprese',
                'Frango assado com batata doce',
                'Peixe ao molho de maracujá',
                'Omelete com salada',
                'Torta de legumes',
                'Hambúrguer de frango com salada',
                'Salada de grão de bico',
                'Creme de abóbora',
                'Peixe grelhado com legumes',
                'Risoto de frango com legumes',
                'Cuscuz marroquino',
                'Salada de quinoa com frango',
                'Strogonoff de legumes',
                'Wrap de frango',
                'Macarrão de abobrinha com molho de tomate',
                'Frango à parmegiana',
                'Quiche de espinafre',
                'Salada de camarão',
                'Peito de frango recheado',
            ]),
            'ceia' => $this->faker->randomElement([
                'Iogurte natural',
                'Frutas',
                'Pão integral com queijo',
                'Gelatina',
                'Leite desnatado',
                'Vitamina de banana com aveia',
                'Barrinha de cereal',
                'Chá de camomila',
                'Queijo cottage',
                'Torradas integrais',
                'Biscoitos integrais',
                'Creme de avelã',
                'Panqueca de banana',
                'Pão de forma com peito de peru',
                'Shake de proteína',
                'Bolinho de chuva',
                'Mingau de aveia',
                'Pipoca',
                'Cookies de aveia',
                'Smoothie de frutas',
            ]),
        ];
    }
}
